owner: MyEagle-Transport 
repo: status

sites:
  # Web's
  - name: Admin Web
    url: https://admin.miaguila.com/
  - name: Client Web
    url: https://client.miaguila.com/
  - name: KPI Web
    url: https://kpi.prd.miaguila.com/
  - name: Metabase Web
    url: https://metabase.prd.miaguila.com/
  - name: Control Payments Web
    url: https://control.miaguila.com/
  # API's
  - name: Admin Api
    url: https://admin.api.transport.miaguila.com/
  - name: Client Api
    url: https://client.api.prd.miaguila.com/
  - name: Driver Api
    url: https://driver.api.prd.miaguila.com/
  - name: FUEC's Api
    url: https://fuecs.api.transport.miaguila.com/api/v1/pdf
  - name: Routing Batching API
    url: https://routing-batching.api.transport.miaguila.com/status
  - name: Trips Dispatcher API
    url: https://trips-dispatcher.api.prd.miaguila.com/api/v1/health
  - name: Control Payments Api
    url: https://control.api.prd.miaguila.com/api/v1/health
  - name: Fares Api
    url: https://fareschange.api.transport.miaguila.com/status
  - name: Tasks Server Api (Celery)
    url: https://tasks-server.api.transport.miaguila.com/v1/health/
    expectedStatusCodes:
      - 200
#  # Worker's
#  - name: Finding to Unattended Job
#    url:
#  - name: Reserving to Finding Job
#    url:
#  - name: Cron Jobs Server
#    url:
#  - name: Mongo ETL
#    url:



status-website:
  cname: status.prd.miaguila.com
  logoUrl: https://www.miaguila.com/favicon.ico
  name: Mi Aguila status 
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration