owner: MyEagle-Transport 
repo: status

sites:
  # Web's
  - name: Admin Web
    url: https://admin.miaguila.com/
  - name: Client Web
    url: https://client.miaguila.com/
  - name: KPI Web
    url: https://kpi.prd.miaguila.com/
  - name: Metabase Web
    url: https://metabase.prd.miaguila.com/
  - name: Control Payments Web
    url: https://control.miaguila.com/
  # API's
  - name: Admin Api
    url: https://admin.api.transport.miaguila.com/
  - name: Client Api
    url: https://client.api.prd.miaguila.com/
  - name: Driver Api
    url: https://driver.api.prd.miaguila.com/
  - name: FUEC's Api
    url: https://fuecs.api.transport.miaguila.com/api/v1/pdf
  - name: Routing Batching API
    url: https://routing-batching.api.transport.miaguila.com/status
  - name: Trips Dispatcher API
    url: https://trips-dispatcher.api.prd.miaguila.com/api/v1/health
  - name: Control Payments Api
    url: https://control.api.prd.miaguila.com/api/v1/health
  - name: Fares Api
    url: https://fareschange.api.transport.miaguila.com/status
  - name: Tasks Server Api (Celery)
    url: https://tasks-server.api.transport.miaguila.com/v1/health/
#  # Worker's
#  - name: Finding to Unattended Job
#    url:
#  - name: Reserving to Finding Job
#    url:
#  - name: Cron Jobs Server
#    url:
#  - name: Mongo ETL
#    url:



status-website:
  cname: status.prd.miaguila.com
  logoUrl: https://www.miaguila.com/favicon.ico
  name: Estado de Servicios - Mi Aguila
  introTitle: "Monitor de Estado en Tiempo Real"
  introMessage: Bienvenido al centro de monitoreo de la plataforma de transporte **Mi Aguila**. Aquí puedes consultar el estado operacional de todos nuestros servicios, aplicaciones web y APIs. Los datos se actualizan automáticamente cada 2 minutos para garantizar información precisa y oportuna sobre la disponibilidad de nuestra infraestructura tecnológica.
  navbar:
    - title: Estado de Servicios
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Notificaciones de Slack cuando un servicio está caído
notifications:
  - type: slack
    webhook-url: $SLACK_WEBHOOK_URL

# Asignar issues automáticamente cuando un servicio cae
assignees:
  - juanpaconpa

# Personalización de commits
commitMessages:
  commitAuthorName: "Mi Aguila Status Bot"
  commitAuthorEmail: "noreply@miaguila.com"

# Frecuencia de verificación de servicios
workflowSchedule:
  uptime: "*/2 * * * *"        # Verificar estado cada 2 minutos
  responseTime: "0 */6 * * *"  # Actualizar tiempos de respuesta cada 6 horas
  graphs: "0 0 * * *"          # Generar gráficos diariamente a medianoche
  staticSite: "0 1 * * *"      # Actualizar sitio web diariamente a la 1:00 AM